logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host:  # 主机名
    port: 5672   # 端口
    virtual-host: /  #虚拟主机
    username: starQeem  # 用户名
    password:   # 密码 # 每次只能获取一条消息，处理完成才能获取下一个消息
    listener:
      simple:
        prefetch: 1